name: Test BUILD_ROLE
permissions:
  id-token: write
on:
  push:
    branches:
      - 'test/build_role'
jobs:
  build_role:
    runs-on: ubuntu-latest
    steps:
        - name: 📦 Checkout Repository
          uses: actions/checkout@v6
        
        - name: 🟦 Install AWS CLI
          uses: aws-actions/configure-aws-credentials@v6
          with:
            role-to-assume: ${{ secrets.BUILD_ROLE }}
            role-duration-seconds: 900
            role-skip-session-tagging: true
            aws-region: "us-east-1"

        - name: 🛠️ Set up Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: '1.13.0'

        - name: Test terraform
          working-directory: examples/complete
          run:
            terraform init
            terraform plan -detailed-exitcode -no-color -out=tfplan > plan.txt 2>&1 || exitcode=$?
            grep -E '^Plan:|^No changes' plan.txt || echo "No changes."
          