name: Test BUILD_ROLE with tf-checks
permissions:
  id-token: write
on:
  push:
    branches:
      - 'test/build_role'
jobs:
  tf-checks-build-role:
    uses: ./.github/workflows/tf-checks.yml
    with:
      working_directory: './examples/complete/'
      provider: aws
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}